import db from '@adonisjs/lucid/services/db'
import Ecole from '#models/ecole'
import User from '#models/user'
import Eleve from '#models/eleve'
export default class DashboardService {
  async getFullDashboard() {
    const [statistics, schools, users, recentSchools, recentAdministrators, topSchools, schoolsStatistics, activities, monthlySchools, monthlyUsers, systemHealth] = await Promise.all([this.getStatistics(), this.getSchoolsByStatus(), this.getUsersByRole(), this.getRecentSchools(5), this.getRecentAdministrators(5), this.getTopSchools(5), this.getSchoolsWithStatistics(), this.getRecentActivities(10), this.getMonthlySchools(new Date().getFullYear()), this.getMonthlyUsers(new Date().getFullYear()), this.getSystemHealth()])
    return { success: true, data: { statistics, schools, users, recentSchools, recentAdministrators, topSchools, schoolsStatistics, activities, monthlySchools, monthlyUsers, systemHealth } }
  }
  async getStatistics() {
    const [schools, users, students, activeSchools, suspendedSchools, admins] = await Promise.all([Ecole.query().count('* as total'), User.query().whereNull('deleted_at').count('* as total'), Eleve.query().count('* as total'), Ecole.query().where('statut', 'ACTIF').count('* as total'), Ecole.query().where('statut', 'SUSPENDU').count('* as total'), User.query().whereNull('deleted_at').whereHas('ecoles', q => q.wherePivot('role', 'ADMIN_ECOLE')).where('statut', 'ACTIF').count('* as total')])
    return { totalSchools: Number(schools[0].$extras.total), totalUsers: Number(users[0].$extras.total), totalStudents: Number(students[0].$extras.total), activeSchools: Number(activeSchools[0].$extras.total), suspendedSchools: Number(suspendedSchools[0].$extras.total), activeAdministrators: Number(admins[0].$extras.total) }
  }
  async getSchoolsByStatus() { const rows = await Ecole.query().select('statut').count('* as total').groupBy('statut'); return rows.map(row => ({ statut: row.statut, total: Number(row.$extras.total) })) }
  async getUsersByRole() { const [admins, teachers, parents, students, total] = await Promise.all([User.query().whereNull('deleted_at').whereHas('ecoles', q => q.wherePivot('role', 'ADMIN_ECOLE')).count('* as total'), User.query().whereNull('deleted_at').whereHas('ecoles', q => q.wherePivot('role', 'ENSEIGNANT')).count('* as total'), User.query().whereNull('deleted_at').whereHas('ecoles', q => q.wherePivot('role', 'PARENT')).count('* as total'), User.query().whereNull('deleted_at').whereHas('ecoles', q => q.wherePivot('role', 'ELEVE')).count('* as total'), User.query().whereNull('deleted_at').count('* as total')]); return { total: Number(total[0].$extras.total), admins: Number(admins[0].$extras.total), teachers: Number(teachers[0].$extras.total), parents: Number(parents[0].$extras.total), students: Number(students[0].$extras.total) } }
  async getRecentSchools(limit = 5) { const rows = await Ecole.query().orderBy('created_at', 'desc').limit(Math.min(Math.max(limit, 1), 50)); return Promise.all(rows.map(row => this.schoolSummary(row))) }
  async getRecentAdministrators(limit = 5) { const rows = await User.query().whereNull('deleted_at').whereHas('ecoles', q => q.wherePivot('role', 'ADMIN_ECOLE')).preload('ecoles', q => q.pivotColumns(['role', 'statut'])).orderBy('created_at', 'desc').limit(Math.min(Math.max(limit, 1), 50)); return rows.map(user => ({ id: user.id, nom: user.nom, prenom: user.prenom, email: user.email, statut: user.statut, createdAt: user.createdAt, ecoles: user.ecoles })) }
  async getTopSchools(limit = 5) { const rows = await Ecole.query().orderBy('created_at', 'desc').limit(Math.min(Math.max(limit, 1), 50)); return Promise.all(rows.map(row => this.schoolSummary(row))) }
  async getSchoolsWithStatistics() { const rows = await Ecole.all(); return Promise.all(rows.map(row => this.schoolSummary(row))) }
  async getRecentActivities(limit = 10) { const [schools, users] = await Promise.all([Ecole.query().orderBy('created_at', 'desc').limit(10), User.query().whereNull('deleted_at').orderBy('created_at', 'desc').limit(10)]); return [...schools.map(row => ({ type: 'school_created', date: row.createdAt, label: `École créée : ${row.nom}` })), ...users.map(row => ({ type: 'user_created', date: row.createdAt, label: `Utilisateur créé : ${row.prenom} ${row.nom}` }))].sort((a, b) => b.date.toMillis() - a.date.toMillis()).slice(0, limit) }
  async getMonthlySchools(year: number) { const rows = await db.from('ecoles').select(db.raw("EXTRACT(MONTH FROM created_at)::int as month"), db.raw('COUNT(*)::int as total')).whereRaw('EXTRACT(YEAR FROM created_at) = ?', [year]).groupBy('month').orderBy('month'); return this.fillMonths(rows) }
  async getMonthlyUsers(year: number) { const rows = await db.from('users').select(db.raw("EXTRACT(MONTH FROM created_at)::int as month"), db.raw('COUNT(*)::int as total')).whereNull('deleted_at').whereRaw('EXTRACT(YEAR FROM created_at) = ?', [year]).groupBy('month').orderBy('month'); return this.fillMonths(rows) }
  async getSystemHealth() { const started = Date.now(); let database = 'ok'; try { await db.rawQuery('select 1') } catch { database = 'error' } return { status: database === 'ok' ? 'healthy' : 'degraded', database, responseTimeMs: Date.now() - started, checkedAt: new Date().toISOString() } }
  private fillMonths(rows: any[]) { const map = new Map(rows.map(row => [Number(row.month), Number(row.total)])); return Array.from({ length: 12 }, (_, i) => ({ month: i + 1, total: map.get(i + 1) ?? 0 })) }
  private async schoolSummary(row: Ecole) { const [students, admins] = await Promise.all([row.related('eleves').query().count('* as total'), row.related('utilisateurs').query().wherePivot('role', 'ADMIN_ECOLE').wherePivot('statut', 'ACTIF').count('* as total')]); return { id: row.id, nom: row.nom, code: row.code, statut: row.statut, ville: row.ville, province: row.province, nombreEleves: Number(students[0].$extras.total), nombreAdministrateurs: Number(admins[0].$extras.total), createdAt: row.createdAt } }
}
