/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  ForgotPasswords: () => import('#controllers/forgot_passwords_controller'),
  GoogleAuths: () => import('#controllers/google_auths_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  schoolAdmin: {
    Dashboard: () => import('#controllers/school_admin/dashboard_controller'),
  },
  Session: () => import('#controllers/session_controller'),
  superAdmin: {
    Administrateurs: () => import('#controllers/super_admin/administrateurs_controller'),
    Dashboard: () => import('#controllers/super_admin/dashboard_controller'),
    Ecoles: () => import('#controllers/super_admin/ecoles_controller'),
    Reports: () => import('#controllers/super_admin/reports_controller'),
    Statistics: () => import('#controllers/super_admin/statistics_controller'),
    SuperAdmin: () => import('#controllers/super_admin/super_admin_controller'),
  },
}
