/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccessTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'ecoleId', 'id', 'role', 'updatedAt', 'userId'] as const
  $columns = AccessTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare ecoleId: bigint | number
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: bigint | number
}

export class ClassSchema extends BaseModel {
  static $columns = ['anneeScolaire', 'createdAt', 'ecoleId', 'id', 'niveauId', 'nom', 'statut', 'updatedAt'] as const
  $columns = ClassSchema.$columns
  @column()
  declare anneeScolaire: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare ecoleId: bigint | number
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare niveauId: bigint | number
  @column()
  declare nom: string
  @column()
  declare statut: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CommuniqueSchema extends BaseModel {
  static $columns = ['auteurId', 'cible', 'contenu', 'createdAt', 'datePublication', 'ecoleId', 'fichier', 'id', 'statut', 'titre', 'updatedAt'] as const
  $columns = CommuniqueSchema.$columns
  @column()
  declare auteurId: bigint | number
  @column()
  declare cible: string | null
  @column()
  declare contenu: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare datePublication: DateTime | null
  @column()
  declare ecoleId: bigint | number
  @column()
  declare fichier: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare statut: string | null
  @column()
  declare titre: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DevoirEleveSchema extends BaseModel {
  static $columns = ['createdAt', 'dateLecture', 'devoirId', 'eleveId', 'id', 'statut', 'updatedAt'] as const
  $columns = DevoirEleveSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare dateLecture: DateTime | null
  @column()
  declare devoirId: bigint | number
  @column()
  declare eleveId: bigint | number
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare statut: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DevoirSchema extends BaseModel {
  static $columns = ['classeId', 'createdAt', 'dateLimite', 'datePublication', 'description', 'ecoleId', 'enseignantId', 'fichier', 'id', 'matiereId', 'statut', 'titre', 'updatedAt'] as const
  $columns = DevoirSchema.$columns
  @column()
  declare classeId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare dateLimite: DateTime | null
  @column.dateTime()
  declare datePublication: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare ecoleId: bigint | number
  @column()
  declare enseignantId: bigint | number
  @column()
  declare fichier: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare matiereId: bigint | number
  @column()
  declare statut: string | null
  @column()
  declare titre: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EcoleUserSchema extends BaseModel {
  static $columns = ['createdAt', 'ecoleId', 'id', 'role', 'statut', 'updatedAt', 'userId'] as const
  $columns = EcoleUserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare ecoleId: bigint | number
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare role: string
  @column()
  declare statut: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: bigint | number
}

export class EcoleSchema extends BaseModel {
  static $columns = ['adresse', 'code', 'createdAt', 'description', 'email', 'id', 'logo', 'nom', 'pays', 'statut', 'telephone', 'updatedAt', 'ville'] as const
  $columns = EcoleSchema.$columns
  @column()
  declare adresse: string | null
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare logo: string | null
  @column()
  declare nom: string
  @column()
  declare pays: string | null
  @column()
  declare statut: string | null
  @column()
  declare telephone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare ville: string | null
}

export class EleveSchema extends BaseModel {
  static $columns = ['classeId', 'createdAt', 'dateNaissance', 'ecoleId', 'id', 'matricule', 'photo', 'sexe', 'statut', 'updatedAt', 'userId'] as const
  $columns = EleveSchema.$columns
  @column()
  declare classeId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dateNaissance: DateTime | null
  @column()
  declare ecoleId: bigint | number
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare matricule: string
  @column()
  declare photo: string | null
  @column()
  declare sexe: string | null
  @column()
  declare statut: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: bigint | number | null
}

export class ExerciceSchema extends BaseModel {
  static $columns = ['classeId', 'createdAt', 'description', 'ecoleId', 'enseignantId', 'fichier', 'id', 'matiereId', 'statut', 'titre', 'updatedAt'] as const
  $columns = ExerciceSchema.$columns
  @column()
  declare classeId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare ecoleId: bigint | number
  @column()
  declare enseignantId: bigint | number
  @column()
  declare fichier: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare matiereId: bigint | number
  @column()
  declare statut: string | null
  @column()
  declare titre: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MatiereSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'ecoleId', 'id', 'nom', 'statut', 'updatedAt'] as const
  $columns = MatiereSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare ecoleId: bigint | number
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare nom: string
  @column()
  declare statut: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class NiveauSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'ecoleId', 'id', 'nom', 'statut', 'updatedAt'] as const
  $columns = NiveauSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare ecoleId: bigint | number
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare nom: string
  @column()
  declare statut: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ParentEleveSchema extends BaseModel {
  static $columns = ['createdAt', 'eleveId', 'id', 'parentId', 'relation', 'updatedAt'] as const
  $columns = ParentEleveSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eleveId: bigint | number
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare parentId: bigint | number
  @column()
  declare relation: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserContextSchema extends BaseModel {
  static $columns = ['active', 'createdAt', 'ecoleId', 'id', 'updatedAt', 'userId'] as const
  $columns = UserContextSchema.$columns
  @column()
  declare active: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare ecoleId: bigint | number
  @column({ isPrimary: true })
  declare id: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: bigint | number
}

export class UserSchema extends BaseModel {
  static $columns = ['address', 'avatarUrl', 'bio', 'createdAt', 'deletedAt', 'email', 'googleId', 'id', 'isVerified', 'lastLoginAt', 'nom', 'password', 'postnom', 'prenom', 'pseudo', 'resetPasswordExpiresAt', 'resetPasswordToken', 'sexe', 'statut', 'systemRole', 'telephone', 'tokenVerification', 'tokenVerificationExpiresAt', 'twoFactorCode', 'twoFactorExpiresAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare avatarUrl: string | null
  @column()
  declare bio: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare googleId: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isVerified: boolean | null
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column()
  declare nom: string
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare postnom: string | null
  @column()
  declare prenom: string
  @column()
  declare pseudo: string | null
  @column.dateTime()
  declare resetPasswordExpiresAt: DateTime | null
  @column()
  declare resetPasswordToken: string | null
  @column()
  declare sexe: string | null
  @column()
  declare statut: string | null
  @column()
  declare systemRole: string | null
  @column()
  declare telephone: string | null
  @column()
  declare tokenVerification: string | null
  @column.dateTime()
  declare tokenVerificationExpiresAt: DateTime | null
  @column()
  declare twoFactorCode: string | null
  @column.dateTime()
  declare twoFactorExpiresAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
